create database social_network;
use social_network;
CREATE TABLE users (
id VARCHAR(255) PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
id VARCHAR(255) PRIMARY KEY,
roomId VARCHAR(255) NOT NULL ,
username VARCHAR(255) NOT NULL ,
message VARCHAR(255) ,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);